### ISSUE TITLE
On certain breached websites the doorhanger does not appear

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/blurts-addon#37]
[Affected versions]:
- Firefox 60.0.2
- Firefox Monitor 0.01, all branches

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Monitor installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to the https://8tracks.com/ page.
3. Observe the behavior.

[Expected result]:
- The page is correctly loaded.
- The Firefox Monitor Alert doorhanger appears.

[Actual result]:
- The page is correctly loaded.
- The Firefox Monitor Alert doorhanger does not appear.

[Notes]:
- This issue is also reproducible on the following websites, from Firefox Monitor HIBP Breaches list: https://www.17173.com/, http://binweevils.com/, https://www.bestialitysextaboo.com/, http://botoflegends.com/, https://www.cashcrate.com/, http://en.cdprojektred.com/, http://www.co188.com/, http://splash.coachella.com/, http://crackingforum.com/, https://www.dominos.be/, https://flvs.net/, https://en.gamigo.com/, http://hiapk.com/, https://www.ilikecheats.net/, https://www.malwarebytes.com/, http://www.mdpi.com/, https://www.ownedcore.com/, https://www.smogon.com/, https://www.taringa.net/, http://www.tgbus.com/, http://www.underworldempireforums.com/, http://viewfines.co.za/, https://www.wildstar-online.com, https://xhamster.com/.
- Also, I’ve encountered this issue for [these websites](https://docs.google.com/spreadsheets/d/1VkRTJeP9TcTowuhgM55P4UiWTgA6JM4YxPX7mdXVHXs/edit?usp=sharing) from the same list, but I was automatically redirected to a different URL. 
- Here is a screen recording with this issue:
![no doornahger displayed](https://user-images.githubusercontent.com/31244235/41468144-9748506e-70b1-11e8-87c9-a17007e7e509.gif)

**Comment by nhnt11** [comment]
This is fixed by 1006de7

**Comment by Softvision-CristinaBadescu** [comment]
I have retested this issue using the latest "Firefox Monitor" add-on (0.01 custom built on 28.06.2018) and it seems that it is partially fixed. The doorhangers are still not displayed on certains websites, such as: "https://www.malwarebytes.com/", "http://www.co188.com/" and "https://www.ownedcore.com/". Verified on Windows 7 x64, using Firefox 61.0 unbranded build.

Considering this, I'm going to reopen the issue.
![breach alerts - 37 - partially fixed](https://user-images.githubusercontent.com/31244235/42034365-79db4270-7ae8-11e8-859c-3414a41b4465.gif)

**Comment by nhnt11** [comment]
For malwarebytes.com, this is because the breach data we have is for malwarebytes.org. This is not actionable right now.

For co188.com, the popup isn't showing up because the page takes forever to finish loading. The popup should be displayed once the page loads.

For ownedcore.com, the breach data we have has different casing: it's for OwnedCore.com. I can fix this by forcing lower case.

**Comment by pdehaan** [comment]
Re: OwnedCore.com, it looks like that was the only instance of a non-lowercase domain name.

```js
const breaches = require("./src/breaches.json");

breaches.map(({Domain, Title}) => ({Domain, Title}))
  .filter(({Domain}) => Domain.length && !/^[a-z\d].*$/.test(Domain))
  .forEach(({Domain, Title}) => console.log({Domain, Title}));
```

```sh
$ node lint-domain.js

# { Domain: 'OwnedCore.com', Title: 'OwnedCore' }
```

**Comment by pdehaan** [comment]
> For co188.com, the popup isn't showing up because the page takes forever to finish loading. The popup should be displayed once the page loads.

Filed as #85 _"Display doorhanger sooner?"_

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible on "https://www.ownedcore.com" website, using the latest version of the "Firefox Monitor" add-on (1.0 custom built on 2018-06-29), on the latest Firefox Release 61.0. Verified on Windows 10 x64.
